### ISSUE TITLE
How is the endpoint defined for basyx

### ISSUE THREAD

**Issue by ct2034** [eclipse-digitaltwin/aaswc#1]
I am not able to access the basyx registry from this.
I do: http://localhost:8083/registryBrowser.html?endpoint=http://localhost:8082/registry/api/v1/registry

Note: all components are set up in docker and work by themselves but I can not make the webclient access the registry.
I am using `eclipsebasyx/aas-registry:1.1.0` 
Note: I think I got CORS set up correctly.

The registry seems to be queried but prints out this: 
```
09:13:31.859 [http-nio-4001-exec-10] DEBUG org.eclipse.basyx.vab.protocol.http.server.VABHTTPInterface - Exception in HTTP-GET. Response-code: 400
org.eclipse.basyx.vab.exception.provider.MalformedRequestException: Path  not recognized as aggregator path. Has to start with shells
	at org.eclipse.basyx.aas.aggregator.restapi.AASAggregatorProvider.stripPrefix(AASAggregatorProvider.java:70)
	at org.eclipse.basyx.aas.aggregator.restapi.AASAggregatorProvider.getValue(AASAggregatorProvider.java:112)
	at org.eclipse.basyx.vab.coder.json.provider.JSONProvider.processBaSysGet(JSONProvider.java:191)
	at org.eclipse.basyx.vab.protocol.http.server.VABHTTPInterface.doGet(VABHTTPInterface.java:130)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
	at org.eclipse.basyx.vab.protocol.http.server.BasysHTTPServlet.service(BasysHTTPServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by ct2034** [comment]
Okay, CORS was obviously not setup correctly but thanks to https://github.com/eclipse-basyx/basyx-java-components/pull/97 there is the [1.2.0-SNAPSHOT-CORS](https://hub.docker.com/layers/aas-registry/eclipsebasyx/aas-registry/1.2.0-SNAPSHOT-CORS/images/sha256-fe85f8d4f154954bad47d81a0e3d8254948112b0555f3566b2416bc0de4593a8?context=explore) tag of the registry image. And with that is works. :)
